import type { User, Note } from './types';

export const mockUsers: User[] = [
  { id: 'user-1', name: 'Alice Johnson', avatarUrl: 'https://i.pravatar.cc/150?u=user-1' },
  { id: 'user-2', name: 'Bob Williams', avatarUrl: 'https://i.pravatar.cc/150?u=user-2' },
  { id: 'user-3', name: 'Charlie Brown', avatarUrl: 'https://i.pravatar.cc/150?u=user-3' },
  { id: 'user-4', name: 'Diana Miller', avatarUrl: 'https://i.pravatar.cc/150?u=user-4' },
];

export const mockSubjects: string[] = ['Mathematics', 'Digital Logic', 'Data Structures', 'Operating Systems', 'Computer Networks', 'Database Systems', 'Software Engineering', 'Machine Learning'];
export const mockSemesters: number[] = [1, 2, 3, 4, 5, 6, 7, 8];
export const mockCourses: string[] = ['B.Tech CSE', 'B.Tech ECE', 'B.Tech ME'];
export const mockBatches: string[] = ['2020-2024', '2021-2025', '2022-2026', '2023-2027'];


export const mockNotes: Note[] = [
  {
    id: 'note-1',
    title: 'Advanced Calculus Cheatsheet',
    category: 'note',
    subject: 'Mathematics',
    semester: 4,
    course: 'B.Tech CSE',
    batch: '2021-2025',
    uploader: mockUsers[0],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 125,
    dislikes: 5,
    averageRating: 4.8,
    ratingsCount: 30,
    downloads: 450,
    feedback: [
      { id: 'fb-1-1', user: mockUsers[1], rating: 5, comment: 'This is incredibly helpful, thanks for sharing!', createdAt: new Date('2023-10-16T11:00:00Z') },
      { id: 'fb-1-2', user: mockUsers[2], rating: 4, comment: 'A small correction on page 2, the formula should be x^2 not x^3. Otherwise, fantastic!', createdAt: new Date('2023-10-17T09:25:00Z') },
      { id: 'fb-1-3', user: mockUsers[3], rating: 5, comment: 'Saved my grade. You are a hero.', createdAt: new Date('2023-10-18T14:10:00Z') },
    ],
    qna: [
      {
        id: 'q-1-1',
        user: mockUsers[3],
        question: 'Is the formula for the derivative of sin(x) included in this cheatsheet?',
        createdAt: new Date('2023-10-18T15:00:00Z'),
        answers: [
          {
            id: 'a-1-1-1',
            user: mockUsers[0],
            text: 'Yes, it is on page 3 under the "Trigonometric Derivatives" section. The derivative of sin(x) is cos(x).',
            upvotes: 15,
            createdAt: new Date('2023-10-18T15:30:00Z'),
          },
          {
            id: 'a-1-1-2',
            user: mockUsers[2],
            text: 'Found it! Thanks, that was helpful.',
            upvotes: 3,
            createdAt: new Date('2023-10-18T16:00:00Z'),
          }
        ]
      },
      {
        id: 'q-1-2',
        user: mockUsers[1],
        question: "Can anyone explain L'Hôpital's Rule in simpler terms?",
        createdAt: new Date('2023-10-19T10:00:00Z'),
        answers: []
      }
    ],
    createdAt: new Date('2023-10-15T10:00:00Z'),
  },
  {
    id: 'note-2',
    title: 'Digital Logic Design Fundamentals',
    category: 'note',
    subject: 'Digital Logic',
    semester: 5,
    course: 'B.Tech CSE',
    batch: '2020-2024',
    uploader: mockUsers[1],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 98,
    dislikes: 12,
    averageRating: 4.5,
    ratingsCount: 25,
    downloads: 320,
    feedback: [
        { id: 'fb-2-1', user: mockUsers[0], rating: 5, comment: 'Really clear explanations of complex topics.', createdAt: new Date('2023-11-02T10:00:00Z') },
    ],
    qna: [],
    createdAt: new Date('2023-11-01T14:30:00Z'),
  },
  {
    id: 'note-3',
    title: 'Data Structures & Algorithms Summary',
    category: 'note',
    subject: 'Data Structures',
    semester: 3,
    course: 'B.Tech CSE',
    batch: '2021-2025',
    uploader: mockUsers[2],
    fileUrl: '#',
    fileType: 'doc',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 210,
    dislikes: 3,
    averageRating: 4.9,
    ratingsCount: 55,
    downloads: 890,
    feedback: [
      { id: 'fb-3-1', user: mockUsers[3], rating: 5, comment: 'The Big O notation table is perfect.', createdAt: new Date('2023-09-21T18:45:00Z') },
      { id: 'fb-3-2', user: mockUsers[0], rating: 5, comment: 'I finally understand recursion. Thank you!', createdAt: new Date('2023-09-22T12:00:00Z') },
    ],
    qna: [],
    createdAt: new Date('2023-09-20T09:00:00Z'),
  },
  {
    id: 'note-4',
    title: 'Operating Systems Concepts',
    category: 'note',
    subject: 'Operating Systems',
    semester: 2,
    course: 'B.Tech ECE',
    batch: '2022-2026',
    uploader: mockUsers[3],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 75,
    dislikes: 8,
    averageRating: 4.2,
    ratingsCount: 18,
    downloads: 210,
    feedback: [],
    qna: [],
    createdAt: new Date('2023-10-05T18:00:00Z'),
  },
  {
    id: 'note-5',
    title: 'Intro to Computer Networks',
    category: 'note',
    subject: 'Computer Networks',
    semester: 1,
    course: 'B.Tech CSE',
    batch: '2023-2027',
    uploader: mockUsers[0],
    fileUrl: '#',
    fileType: 'doc',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 50,
    dislikes: 2,
    averageRating: 4.6,
    ratingsCount: 15,
    downloads: 150,
    feedback: [],
    qna: [],
    createdAt: new Date('2024-01-10T11:00:00Z'),
  },
  {
    id: 'note-6',
    title: 'Database Systems Basics',
    category: 'note',
    subject: 'Database Systems',
    semester: 1,
    course: 'B.Tech CSE',
    batch: '2023-2027',
    uploader: mockUsers[1],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 150,
    dislikes: 10,
    averageRating: 4.7,
    ratingsCount: 40,
    downloads: 600,
    feedback: [],
    qna: [],
    createdAt: new Date('2024-02-01T16:20:00Z'),
  },
  {
    id: 'note-7',
    title: 'Software Engineering Principles',
    category: 'note',
    subject: 'Software Engineering',
    semester: 4,
    course: 'B.Tech CSE',
    batch: '2021-2025',
    uploader: mockUsers[2],
    fileUrl: '#',
    fileType: 'doc',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 88,
    dislikes: 4,
    averageRating: 4.4,
    ratingsCount: 22,
    downloads: 280,
    feedback: [],
    qna: [],
    createdAt: new Date('2024-03-12T13:00:00Z'),
  },
  {
    id: 'note-8',
    title: 'Machine Learning Basics',
    category: 'note',
    subject: 'Machine Learning',
    semester: 6,
    course: 'B.Tech ME',
    batch: '2020-2024',
    uploader: mockUsers[3],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 300,
    dislikes: 15,
    averageRating: 4.9,
    ratingsCount: 70,
    downloads: 1200,
    feedback: [
      { id: 'fb-8-1', user: mockUsers[0], rating: 5, comment: 'This is the best intro to ML I have ever seen.', createdAt: new Date('2024-04-06T10:00:00Z') },
      { id: 'fb-8-2', user: mockUsers[1], rating: 4, comment: 'Could use a bit more on regression models, but overall very solid.', createdAt: new Date('2024-04-06T15:30:00Z') },
    ],
    qna: [],
    createdAt: new Date('2024-04-05T20:00:00Z'),
  },
  {
    id: 'qp-1',
    title: 'Data Structures - PTU Final 2023',
    category: 'questionPaper',
    paperType: 'PTU',
    subject: 'Data Structures',
    semester: 3,
    course: 'B.Tech CSE',
    batch: '2021-2025',
    uploader: mockUsers[0],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 150,
    dislikes: 2,
    averageRating: 4.9,
    ratingsCount: 40,
    downloads: 700,
    feedback: [],
    qna: [],
    createdAt: new Date('2023-12-15T10:00:00Z'),
  },
  {
    id: 'qp-2',
    title: 'Operating Systems - MST1 2024',
    category: 'questionPaper',
    paperType: 'MST1',
    subject: 'Operating Systems',
    semester: 4,
    course: 'B.Tech CSE',
    batch: '2021-2025',
    uploader: mockUsers[1],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 80,
    dislikes: 1,
    averageRating: 4.7,
    ratingsCount: 20,
    downloads: 350,
    feedback: [],
    qna: [],
    createdAt: new Date('2024-02-20T11:00:00Z'),
  },
  {
    id: 'qp-3',
    title: 'Computer Networks - MST2 2024',
    category: 'questionPaper',
    paperType: 'MST2',
    subject: 'Computer Networks',
    semester: 5,
    course: 'B.Tech CSE',
    batch: '2020-2024',
    uploader: mockUsers[2],
    fileUrl: '#',
    fileType: 'pdf',
    thumbnailUrl: 'https://placehold.co/400x300.png',
    likes: 95,
    dislikes: 5,
    averageRating: 4.6,
    ratingsCount: 25,
    downloads: 410,
    feedback: [],
    qna: [],
    createdAt: new Date('2024-04-10T14:00:00Z'),
  }
];
