import type { User, Note } from './types';

export const mockUsers: User[] = [
  { id: 'user-1', name: 'Alice Johnson', avatarUrl: 'https://i.pravatar.cc/150?u=user-1' },
  { id: 'user-2', name: 'Bob Williams', avatarUrl: 'https://i.pravatar.cc/150?u=user-2' },
  { id: 'user-3', name: 'Charlie Brown', avatarUrl: 'https://i.pravatar.cc/150?u=user-3' },
  { id: 'user-4', name: 'Diana Miller', avatarUrl: 'https://i.pravatar.cc/150?u=user-4' },
];

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    title: 'Advanced Calculus Cheatsheet',
    subject: 'Mathematics',
    semester: 4,
    uploader: mockUsers[0],
    fileUrl: '#',
    fileType: 'pdf',
    likes: 125,
    dislikes: 5,
    averageRating: 4.8,
    ratingsCount: 30,
    downloads: 450,
    feedback: [
      { id: 'fb-1-1', user: mockUsers[1], rating: 5, comment: 'This is incredibly helpful, thanks for sharing!', createdAt: new Date('2023-10-16T11:00:00Z') },
      { id: 'fb-1-2', user: mockUsers[2], rating: 4, comment: 'A small correction on page 2, the formula should be x^2 not x^3. Otherwise, fantastic!', createdAt: new Date('2023-10-17T09:25:00Z') },
      { id: 'fb-1-3', user: mockUsers[3], rating: 5, comment: 'Saved my grade. You are a hero.', createdAt: new Date('2023-10-18T14:10:00Z') },
    ],
    createdAt: new Date('2023-10-15T10:00:00Z'),
  },
  {
    id: 'note-2',
    title: 'Quantum Mechanics Fundamentals',
    subject: 'Physics',
    semester: 5,
    uploader: mockUsers[1],
    fileUrl: '#',
    fileType: 'pdf',
    likes: 98,
    dislikes: 12,
    averageRating: 4.5,
    ratingsCount: 25,
    downloads: 320,
    feedback: [
        { id: 'fb-2-1', user: mockUsers[0], rating: 5, comment: 'Really clear explanations of complex topics.', createdAt: new Date('2023-11-02T10:00:00Z') },
    ],
    createdAt: new Date('2023-11-01T14:30:00Z'),
  },
  {
    id: 'note-3',
    title: 'Data Structures & Algorithms Summary',
    subject: 'Computer Science',
    semester: 3,
    uploader: mockUsers[2],
    fileUrl: '#',
    fileType: 'doc',
    likes: 210,
    dislikes: 3,
    averageRating: 4.9,
    ratingsCount: 55,
    downloads: 890,
    feedback: [
      { id: 'fb-3-1', user: mockUsers[3], rating: 5, comment: 'The Big O notation table is perfect.', createdAt: new Date('2023-09-21T18:45:00Z') },
      { id: 'fb-3-2', user: mockUsers[0], rating: 5, comment: 'I finally understand recursion. Thank you!', createdAt: new Date('2023-09-22T12:00:00Z') },
    ],
    createdAt: new Date('2023-09-20T09:00:00Z'),
  },
  {
    id: 'note-4',
    title: 'Organic Chemistry Reaction Mechanisms',
    subject: 'Chemistry',
    semester: 2,
    uploader: mockUsers[3],
    fileUrl: '#',
    fileType: 'pdf',
    likes: 75,
    dislikes: 8,
    averageRating: 4.2,
    ratingsCount: 18,
    downloads: 210,
    feedback: [],
    createdAt: new Date('2023-10-05T18:00:00Z'),
  },
  {
    id: 'note-5',
    title: 'World History: The Modern Era',
    subject: 'History',
    semester: 1,
    uploader: mockUsers[0],
    fileUrl: '#',
    fileType: 'doc',
    likes: 50,
    dislikes: 2,
    averageRating: 4.6,
    ratingsCount: 15,
    downloads: 150,
    feedback: [],
    createdAt: new Date('2024-01-10T11:00:00Z'),
  },
  {
    id: 'note-6',
    title: 'Introduction to Microeconomics',
    subject: 'Economics',
    semester: 1,
    uploader: mockUsers[1],
    fileUrl: '#',
    fileType: 'pdf',
    likes: 150,
    dislikes: 10,
    averageRating: 4.7,
    ratingsCount: 40,
    downloads: 600,
    feedback: [],
    createdAt: new Date('2024-02-01T16:20:00Z'),
  },
  {
    id: 'note-7',
    title: 'Literary Analysis Guide',
    subject: 'Literature',
    semester: 4,
    uploader: mockUsers[2],
    fileUrl: '#',
    fileType: 'doc',
    likes: 88,
    dislikes: 4,
    averageRating: 4.4,
    ratingsCount: 22,
    downloads: 280,
    feedback: [],
    createdAt: new Date('2024-03-12T13:00:00Z'),
  },
  {
    id: 'note-8',
    title: 'Machine Learning Basics',
    subject: 'Computer Science',
    semester: 6,
    uploader: mockUsers[3],
    fileUrl: '#',
    fileType: 'pdf',
    likes: 300,
    dislikes: 15,
    averageRating: 4.9,
    ratingsCount: 70,
    downloads: 1200,
    feedback: [
      { id: 'fb-8-1', user: mockUsers[0], rating: 5, comment: 'This is the best intro to ML I have ever seen.', createdAt: new Date('2024-04-06T10:00:00Z') },
      { id: 'fb-8-2', user: mockUsers[1], rating: 4, comment: 'Could use a bit more on regression models, but overall very solid.', createdAt: new Date('2024-04-06T15:30:00Z') },
    ],
    createdAt: new Date('2024-04-05T20:00:00Z'),
  },
];
